name: godzeela_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  custom_switch: ^0.0.1
  flutter_svg: ^0.19.0
  google_sign_in: "^4.5.1"
  cloud_firestore: ^0.14.0
  image_picker: ^0.6.7+4
  firebase_storage: ^4.0.0
  firebase_auth: ^0.18.0
  firebase_core: ^0.5.0
  modal_progress_hud: ^0.1.3
  uuid: ^2.0.0
  cached_network_image: ^2.0.0-rc
  flutter_facebook_login: ^3.0.0
  http: ^0.12.2
  flutter_facebook_auth: ^1.0.0
  flutter_switch: any
  path_provider: any
  flutter_launcher_icons: "^0.8.0"
  flutter_launcher_name: "^0.0.1"
  qr_flutter: ^4.0.0
  badges: ^1.2.0
  nfc_in_flutter: 2.0.0
  app_settings: 4.1.0
  flutter_nfc_reader:
    git:
      url: git://github.com/matteocrippa/flutter-nfc-reader.git
      ref: master
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  url_launcher: ^6.0.3
  animated_splash_screen: ^1.1.0
  page_transition: ^2.0.1-nullsafety.0
  bottom_navy_bar: ^6.0.0
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"

flutter_launcher_name:
  name: "Godzeela"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
# flutter:

#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true
flutter:
  uses-material-design: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: assets/Icons/SocialIcons.ttf
    - family: GoogleIcon
      fonts:
        - asset: assets/Icons/GoogleIcon.ttf
    - family: NfcIcon
      fonts:
        - asset: assets/Icons/NfcIcon.ttf
    - family: PassionOne
      fonts:
        - asset: assets/fonts/PassionOne-Black.ttf
        - asset: assets/fonts/PassionOne-Bold.ttf
        - asset: assets/fonts/PassionOne-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-ThinItalic.ttf

    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Medium.otf
    - family: QRIcon
      fonts: 
        - asset: assets/Icons/QRIcon.ttf
    - family: DrawerIcons
      fonts:
        - asset: assets/Icons/DrawerIcons.ttf
  assets:
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
